services:
  pokemon-app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped